Ecommerce-Web/Areas/Admin/Controllers/CategoryController.cs
using Ecommerce_Web.Data;
using Ecommerce_Web.Models.Catalog;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce_Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CategoryController(ApplicationDbContext applicationDbContext)
        {
            _dbContext = applicationDbContext;
        }
        // GET: Category
        public IActionResult Index()
        {
            List<Category> categories = _dbContext.Categories.ToList();
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            // ensure Id exists before any DB operation
            if (string.IsNullOrWhiteSpace(category.Id))
            {
                category.Id = Guid.NewGuid().ToString();
            }
            // Delete old validation of Id
            ModelState.Remove(nameof(Category.Id));

            if (ModelState.IsValid)
            {
                _dbContext.Categories.Add(category);
                _dbContext.SaveChanges();
                TempData["successMessage"] = "Category created successfully!";
                return RedirectToAction("Index");
            }

            TempData["errorMessage"] = "Invalid data. Please try again.";
            return View(category);
        }

        public IActionResult Edit(string? id)
        {
            if(id == null || id.Length == 0)
            {
                TempData["errorMessage"] = "Category not found.";
                return NotFound();
            }

            var editCategory = _dbContext.Categories.
                            FirstOrDefault(category => category.Id == id);

            if(editCategory == null)
            {
                TempData["errorMessage"] = "Category not found.";
                return NotFound();
            }
            return View(editCategory);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            _dbContext.Categories.Update(category);
            _dbContext.SaveChanges();
            TempData["successMessage"] = "Category updated successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string? id)
        {
            if(id == null || id.Length == 0)
            {
                TempData["errorMessage"] = "Category not found.";
                return NotFound();
            }

            var deletedCategory = _dbContext.Categories.
                                  FirstOrDefault(category => category.Id == id);

            if(deletedCategory == null)
            {
                TempData["errorMessage"] = "Category not found.";
                return NotFound();
            }
            return View(deletedCategory);
        }

        [HttpPost]
        public IActionResult Delete(Category category)
        {
            _dbContext.Categories.Remove(category);
            _dbContext.SaveChanges();
            TempData["successMessage"] = "Category deleted successfully!";
            return RedirectToAction("Index");
        }

    }
}

Ecommerce-Web/Areas/Admin/Controllers/ProductController.cs
using Ecommerce_Web.Data;
using Ecommerce_Web.Models;
using Ecommerce_Web.Models.Catalog;
using Ecommerce_Web.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Linq;

namespace Ecommerce_Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly ILogger<ProductController> _logger;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(ApplicationDbContext dbContext, ILogger<ProductController> logger, IWebHostEnvironment webHostEnvironment)
        {
            _dbContext = dbContext;
            _logger = logger;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            // Take Product table from dbContext, join Category table and map to ProductVM
            var products = _dbContext.Products
                .Include(category => category.Category)
                .Select(productVM => new ProductVM
                {
                    Id = productVM.Id,
                    Name = productVM.Name,
                    Price = productVM.Price,
                    CategoryId = productVM.CategoryId,
                    CategoryName = productVM.Category != null ? productVM.Category.Name : string.Empty,
                    CreateAt = productVM.CreateAt,
                    IsActive = productVM.IsActive,
                    ImageUrl = productVM.ImageUrl
                }).ToList();

            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            //Bind categories to dropdown
            var productVM = new ProductVM()
            {
                Categories = _dbContext.Categories
                                       .Select(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Name
                }).ToList()
            };
            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductVM productVM, IFormFile? formFile)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (formFile != null && formFile.Length > 0)
                {
                    // upload image to wwwroot/img/products
                    string uploadsFolder = Path.Combine(wwwRootPath, @"img\products");
                    string fileName = Path.GetFileName(formFile.FileName);
                    var filePath = Path.Combine(uploadsFolder, fileName);

                    try
                    {
                        if (!Directory.Exists(uploadsFolder))
                        {
                            Directory.CreateDirectory(uploadsFolder);
                        }
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            formFile.CopyTo(fileStream);
                        }
                        productVM.ImageUrl = @"\img\products\" + fileName;

                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Image upload error: " + ex.Message);
                        return View(productVM);
                    }
                }

                var product = new Product
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = productVM.Name,
                    Price = productVM.Price,
                    CategoryId = productVM.CategoryId,
                    CreateAt = productVM.CreateAt,
                    IsActive = productVM.IsActive,
                    ImageUrl = productVM.ImageUrl
                };

                _dbContext.Products.Add(product);
                _dbContext.SaveChanges();
                TempData["successMessage"] = "Add product successfully";
            }

            //Reload dropdown of category
            else
            {
                productVM.Categories = _dbContext.Categories
                                       .Select(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Name
                }).ToList();
                TempData["errorMessage"] = "Add Product invalid";
                return View(productVM);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(string? id)
        {
            if (id == null || id.Length == 0)
            {
                TempData["errorMessage"] = "Product not found";
                return NotFound();
            }

            var editProduct = _dbContext.Products.
                              FirstOrDefault(product => product.Id == id);

            if(editProduct == null)
            {
                TempData["errorMessage"] = "Product not found";
                return NotFound();
            }

            ProductVM productVM = new ProductVM
            {
                Id = editProduct.Id,
                Name = editProduct.Name,
                Price = editProduct.Price,
                CategoryId = editProduct.CategoryId,
                CreateAt = editProduct.CreateAt,
                IsActive = editProduct.IsActive,
                ImageUrl = editProduct.ImageUrl,
                Categories = _dbContext.Categories
                             .Select(c => new SelectListItem
                {
                    Value = c.Id,
                    Text = c.Name
                }).ToList()
            };

            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductVM productVM, IFormFile? formFile)
        {

            var updatedProduct = _dbContext.Products
                                 .FirstOrDefault(product => product.Id == productVM.Id);

            if (updatedProduct == null)
            {
                TempData["errorMessage"] = "Not found product";
                return NotFound();
            }

            // Update product
            if (ModelState.IsValid)
            {

                string wwwRootPath = _webHostEnvironment.WebRootPath;
                if (formFile != null && formFile.Length > 0)
                {
                    // upload image to wwwroot/img/products
                    string uploadsFolder = Path.Combine(wwwRootPath, @"img\products");
                    string fileName = Path.GetFileName(formFile.FileName);
                    var filePath = Path.Combine(uploadsFolder, fileName);

                    using(var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        formFile.CopyTo(fileStream);
                    }
                    updatedProduct.ImageUrl = @"\img\products\" + fileName;
                }
                   
                updatedProduct.Name = productVM.Name;
                updatedProduct.Price = productVM.Price;
                updatedProduct.CategoryId = productVM.CategoryId;
                updatedProduct.CreateAt = productVM.CreateAt;
                updatedProduct.IsActive = productVM.IsActive;

               _dbContext.SaveChanges();
               TempData["successMessage"] = "Product updated successfully";
               return RedirectToAction("Index");
            }

            // On error, reload categories and return view
            productVM.Categories = _dbContext.Categories
                                   .Select(cate => new SelectListItem
            {
                Value = cate.Id,
                Text = cate.Name
            }).ToList();

            return View(productVM);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            if(id == null || id.Length == 0)
            {
                TempData["errorMessage"] = "Product not found";
                return NotFound();
            }

            var deletedProduct = await _dbContext.Products
                                 .Include(category => category.Category)
                                 .FirstOrDefaultAsync(product => product.Id == id);

            if (deletedProduct == null)
            {
                TempData["errorMessage"] = "Product not found";
                return NotFound();
            }

            ProductVM productVM = new ProductVM
            {
                Id = deletedProduct.Id,
                Name = deletedProduct.Name,
                Price = deletedProduct.Price,
                CategoryId = deletedProduct.CategoryId,
                CategoryName = deletedProduct.Category.Name != null ? deletedProduct.Category.Name : string.Empty,
                CreateAt = deletedProduct.CreateAt,
                IsActive = deletedProduct.IsActive,
                ImageUrl = deletedProduct.ImageUrl
            };

            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(ProductVM productVM)
        {
            
            if (ModelState.IsValid)
            {
                var productDeleted = _dbContext.Products
                                     .FirstOrDefault(product => product.Id == productVM.Id);

                if (productDeleted == null)
                {
                    TempData["errorMessage"] = "Product not found";
                    return NotFound();
                }

                _dbContext.Products.Remove(productDeleted);
                _dbContext.SaveChanges();

Ecommerce-Web/Areas/User/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Ecommerce_Web.Areas.User.Controllers
{
    public class CartController : Controller
    {
        [Area("User")]
        [Authorize]
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cartItems = new List<object>();

            return View(cartItems);
        }
    }
}

Ecommerce-Web/Views/Shared/PageNotFound.cshtml
@{
    ViewData["Title"] = "Page Not Found";
    Layout = null;
}
<link rel="stylesheet" href="~/css/Components/UI/Redirect.css" asp-append-version="true" />

<div class="error-container">
    <div class="error-box">
        <h1 class="code">404</h1>
        <h2 class="title">The page you are looking for not exist</h2>
        <p class="description">
           Please check your route and try again.
        </p>

        <a asp-controller="Home" asp-action="Index" class="home-btn">Return to home page</a>
    </div>
</div>

Ecommerce-Web/Views/Shared/_Header.cshtml
<header class="main-header">
    <div class="header-container">

        <!-- Logo -->
        <div class="header-logo">
            <a href="/">
                <span class="logo-red">Tien Thanh</span>
                <span class="logo-white">TECHNOLOGY</span>
            </a>
        </div>

        <!-- Search -->
        <div class="header-search">
            <select class="search-category">
                <option>Tất cả danh mục</option>
                <option>Laptop</option>
                <option>PC</option>
                <option>Linh kiện</option>
            </select>

            <input type="text"
                   placeholder="Nhập tên sản phẩm, mã sản phẩm, từ khóa..." />

            <button class="search-btn">
                🔍
            </button>
        </div>

        <!-- Actions -->
        <div class="header-actions">
            <partial name="_LoginPartial" />

            <a asp-area="User" asp-controller="Cart" asp-action="Index" class="header-item">
                🛒
                <span>Giỏ hàng</span>
            </a>
        </div>

    </div>
</header>

Ecommerce-Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Tien Thanh Technology</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Components/Layout/Header.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("_Header")
    <header>
        <nav class="navbar navbar-expand navbar-toggleable-sm navbar-light bg-white box-shadow mb-5">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if(User.IsInRole("Admin"))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                }    
            </div>

        </nav>
        @RenderSection("Styles", required: false)
        @await RenderSectionAsync("Scripts", required: false)
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @await Html.PartialAsync("_Notification")
            @RenderBody()
        </main>
    </div>

    <footer >
        <div class="container">
         
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/img_preview.js" asp-append-version="true"></script>
    <script>
        function closeNotification(button) {
            const notification = button.closest('.notification');
            notification.classList.add('hide');

            setTimeout(() => {
                notification.remove();
            }, 350);
        }
    </script>
</body>
</html>